#[derive(Debug, PartialEq, Clone)]
pub enum Exp {
    Let(String, Box<Exp>, Box<Exp>),
    Select(Vec<String>, Box<Exp>),
    Where(Box<Exp>, Box<Exp>),
    Union(Box<Exp>, Box<Exp>),
    Difference(Box<Exp>, Box<Exp>),
    Product(Box<Exp>, Box<Exp>),
    Table(Box<Exp>, Box<Exp>),
    Row(Box<Exp>, Box<Exp>),
    Cell(String, Box<Exp>),
    Or(Box<Exp>, Box<Exp>),
    Equals(Box<Exp>, Box<Exp>),
    And(Box<Exp>, Box<Exp>),
    Not(Box<Exp>),
    Bool(bool),
    Int(i64),
    Str(String),
    Var(String),
}
